name: Update Quote and Poem
on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  update_quote_and_poem:
    runs-on: ubuntu-latest
    steps:
      - name: Set up the time zone
        run: |
          sudo ln -sf /usr/share/zoneinfo/$TIME_ZONE /etc/localtime
          echo $TIME_ZONE | sudo tee /etc/timezone
          date

      - name: Configure Git
        run: |
          git init
          git config --global user.email "nirmalrokamagar54@gmail.com"
          git config --global user.name "iam-neo"

      - name: Check out repository
        uses: actions/checkout@v2
        with:
          repository: iam-neo/iam-neo

      - name: Run script
        run: |
          chmod +x quote_and_poem.sh
          ./quote_and_poem.sh

      - name: Check README.md status
        run: |
          git status README.md

      - name: Commit and push changes
        run: |
          git pull origin main
          chmod +x quote_and_poem.sh
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
